tf2pickup-org/client

- package-lock.json
- package.json
- src/app/auth/auth-interceptor.service.spec.ts
- src/app/auth/auth-interceptor.service.ts
- src/app/auth/auth.module.ts
- src/app/auth/auth.service.spec.ts
- src/app/auth/auth.service.ts
- src/app/auth/token-store.service.spec.ts
- src/app/auth/token-store.service.ts
- src/app/core/io-client.service.spec.ts
- src/app/core/io-client.service.ts
Handles all token in a better way. Also, shared all the tokens across tabs in a browser.
> feat: token store

- src/app/games/mumble-join-button/mumble-join-button.component.spec.ts
- src/app/games/mumble-join-button/mumble-join-button.component.ts
- src/app/players/models/player-skill.ts
- src/app/players/players.service.spec.ts
- src/app/players/players.service.ts
Adapt the client to server changes.
> feat: adapt server model update

- src/app/queue/queue.effects.spec.ts
- src/app/queue/queue.effects.ts
Fixes ready up dialog login and refreshing the page with ready up state.
> fix: ready up state

- src/app/players/player-details/player-details.component.html
- src/app/players/player-details/player-details.component.spec.ts
- src/app/players/player-details/player-details.component.ts
- src/app/players/player-edit/player-edit.component.spec.ts
- src/app/players/player-edit/player-edit.component.ts
* fix player details cancel button to navigate back in history instead of always  going back to the profile page
* make player edit link an actual link
> fix: player details & edit fixes

- src/app/game-servers/game-server-list/game-server-list.component.ts
- src/app/games/game-details/game-details.component.ts
- src/app/games/game-list/game-list.component.ts
- src/app/players/player-details/player-details.component.ts
- src/app/players/player-edit/player-edit.component.ts
- src/app/players/player-list/player-list.component.ts
- src/app/queue/queue-container/queue-container.component.spec.ts
- src/app/queue/queue-container/queue-container.component.ts
- src/app/queue/queue/queue.component.ts
- src/app/shared/rules/rules.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Sets document title when loading routed components.
> feat: set document title

- src/app/app.module.ts
- src/app/core/models/paginated-list.ts
- src/app/games/game-list/game-list.component.html
- src/app/games/game-list/game-list.component.spec.ts
- src/app/games/game-list/game-list.component.ts
- src/app/games/games.actions.ts
- src/app/games/games.effects.ts
- src/app/games/games.module.ts
- src/app/games/games.reducer.ts
- src/app/games/games.selectors.ts
- src/app/games/games.service.spec.ts
- src/app/games/games.service.ts
- src/app/players/player-details/player-details.component.html
- src/app/players/player-details/player-details.component.spec.ts
- src/app/players/player-details/player-details.component.ts
- src/app/players/players.module.ts
- src/app/players/players.service.spec.ts
- src/app/players/players.service.ts
Adds pagination for:
* game list,
* player's game list.
> feat: lists pagination

- src/app/games/games.actions.ts
- src/app/games/games.effects.ts
- src/app/queue/pre-ready-countdown.service.spec.ts
- src/app/queue/pre-ready-countdown.service.ts
- src/app/queue/pre-ready-up-button/pre-ready-up-button.component.html
- src/app/queue/pre-ready-up-button/pre-ready-up-button.component.scss
- src/app/queue/pre-ready-up-button/pre-ready-up-button.component.spec.ts
- src/app/queue/pre-ready-up-button/pre-ready-up-button.component.ts
- src/app/queue/queue-addons/queue-addons.component.html
- src/app/queue/queue-addons/queue-addons.component.spec.ts
- src/app/queue/queue-addons/queue-addons.component.ts
- src/app/queue/queue-container/queue-container.component.html
- src/app/queue/queue-container/queue-container.component.spec.ts
- src/app/queue/queue-container/queue-container.component.ts
- src/app/queue/queue-status/queue-status.component.html
- src/app/queue/queue-status/queue-status.component.spec.ts
- src/app/queue/queue-status/queue-status.component.ts
- src/app/queue/queue.actions.ts
- src/app/queue/queue.effects.ts
- src/app/queue/queue.module.ts
- src/app/queue/queue.reducer.ts
- src/app/queue/queue.selectors.spec.ts
- src/app/queue/queue.selectors.ts
- src/app/queue/queue/queue.component.scss
- src/app/queue/seconds.pipe.spec.ts
- src/app/queue/seconds.pipe.ts
- src/app/queue/vote-for-map-change-button/vote-for-map-change-button.component.html
- src/app/queue/vote-for-map-change-button/vote-for-map-change-button.component.spec.ts
- src/app/queue/vote-for-map-change-button/vote-for-map-change-button.component.ts
Implements a pre-ready button that lest the user leave the PC for up to 3 minutes without worrying they miss a game.
> feat: pre-ready up

- src/app/app.module.ts
- src/app/core/navigation-bar/navigation-bar.component.html
- src/app/hall-of-fame/hall-of-fame-routing.module.ts
- src/app/hall-of-fame/hall-of-fame.module.ts
- src/app/hall-of-fame/hall-of-fame.service.spec.ts
- src/app/hall-of-fame/hall-of-fame.service.ts
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.html
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.spec.ts
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.ts
- src/app/hall-of-fame/models/hall-of-fame-record.ts
- src/app/hall-of-fame/models/hall-of-fame.ts
> feat: hall of fame

- src/app/players/etf2l-profile-link.pipe.spec.ts
- src/app/players/etf2l-profile-link.pipe.ts
- src/app/players/logs-tf-profile-link.pipe.spec.ts
- src/app/players/logs-tf-profile-link.pipe.ts
- src/app/players/player-details/player-details.component.html
- src/app/players/player-details/player-details.component.spec.ts
- src/app/players/player-list/player-list.component.html
- src/app/players/player-list/player-list.component.spec.ts
- src/app/players/players.module.ts
- src/app/players/steam-profile-link.pipe.spec.ts
- src/app/players/steam-profile-link.pipe.ts
Adds admin badge in player list and profile page. Also, uses pipes to create Steam, ETF2L and logs.tf profile links.
> feat: admin badge

- src/app/auth/auth-error/auth-error.component.ts
- src/app/auth/token-store.service.ts
Fixes handling of authentication errors from backend.
> fix: handle auth errors properly

- src/app/players/player-edit-skill/player-edit-skill.component.html
- src/app/players/player-edit-skill/player-edit-skill.component.spec.ts
Increases the skill range
* previously it was 1-5
* now it's 1-7
> feat: increase skill range

- package-lock.json
- package.json
- src/app/auth/is-admin.guard.spec.ts
- src/app/auth/is-admin.guard.ts
- src/app/core/footer/footer.component.html
- src/app/core/footer/footer.component.spec.ts
- src/app/core/footer/footer.component.ts
- src/app/players/actions/players.actions.ts
- src/app/players/players-routing.module.ts
- src/app/players/players.effects.spec.ts
- src/app/players/players.effects.ts
- src/app/players/players.module.ts
- src/app/players/players.service.spec.ts
- src/app/players/players.service.ts
- src/app/players/reducers/players.reducer.ts
- src/app/players/skill-table/skill-table.component.html
- src/app/players/skill-table/skill-table.component.spec.ts
- src/app/players/skill-table/skill-table.component.ts
- src/styles.scss
Adds a table with all players' assigned skills on every class.
> feat: player skill table

- src/app/game-servers/game-servers.effects.spec.ts
- src/app/players/actions/players.actions.ts
- src/app/players/player-edit/player-edit.component.spec.ts
- src/app/players/player-edit/player-edit.component.ts
- src/app/players/players.effects.spec.ts
- src/app/players/players.effects.ts
- src/app/players/players.service.spec.ts
- src/app/players/players.service.ts
- src/app/players/selectors/players.selectors.spec.ts
- src/app/players/selectors/players.selectors.ts
Fixes an issue which made it impossible  to edit skills for players who had unassigned skills previously.
> fix: edit skills for unassigned players

- src/app/games/game-basic-info/game-basic-info.component.html
- src/app/games/game-basic-info/game-basic-info.component.spec.ts
- src/app/games/game-basic-info/game-basic-info.component.ts
- src/app/games/game-details/game-details.component.html
- src/app/games/game-details/game-details.component.spec.ts
- src/app/games/game-details/game-details.component.ts
- src/app/games/game-summary/game-summary.component.html
- src/app/games/game-summary/game-summary.component.spec.ts
- src/app/games/game-summary/game-summary.component.ts
- src/app/games/game-team-player-list/game-team-player-list.component.html
- src/app/games/game-team-player-list/game-team-player-list.component.scss
- src/app/games/game-team-player-list/game-team-player-list.component.spec.ts
- src/app/games/game-team-player-list/game-team-player-list.component.ts
- src/app/games/games.module.ts
- src/app/games/join-game-info/join-game-info.component.html
- src/app/games/join-game-info/join-game-info.component.spec.ts
- src/app/games/join-game-info/join-game-info.component.ts
- src/app/games/models/game-player.ts
- src/app/games/models/player-connection-status.ts
- src/app/games/models/resolved-game-player.ts
- src/app/games/player-connection-status/player-connection-status.component.html
- src/app/games/player-connection-status/player-connection-status.component.spec.ts
- src/app/games/player-connection-status/player-connection-status.component.ts
Shows a badge indicating at what state of connection to the server the given player is. He might be offline, connecting to the server and fully connected - meaning he's joined the team.
Also, refactors the GameDetailsComponents, splitting it into a number  of smaller components.
> feature: player connection status

- src/app/players/actions/players.actions.ts
- src/app/players/edit-player-role-dialog/edit-player-role-dialog.component.html
- src/app/players/edit-player-role-dialog/edit-player-role-dialog.component.spec.ts
- src/app/players/edit-player-role-dialog/edit-player-role-dialog.component.ts
- src/app/players/player-details/player-details.component.html
- src/app/players/player-details/player-details.component.spec.ts
- src/app/players/player-details/player-details.component.ts
- src/app/players/player-edit/player-edit.component.spec.ts
- src/app/players/player-edit/player-edit.component.ts
- src/app/players/players.effects.spec.ts
- src/app/players/players.effects.ts
- src/app/players/players.module.ts
- src/app/players/players.service.spec.ts
- src/app/players/players.service.ts
- src/app/players/reducers/players.reducer.ts
Adds a dialog that makes it possible to set given user role.
> feat: nominate admins

- src/app/queue/friend-flags.ts
- src/app/queue/models/friendship.ts
- src/app/queue/models/queue-slot.ts
- src/app/queue/models/queue.ts
- src/app/queue/queue-class-slot-list/queue-class-slot-list.component.html
- src/app/queue/queue-class-slot-list/queue-class-slot-list.component.spec.ts
- src/app/queue/queue-class-slot-list/queue-class-slot-list.component.ts
- src/app/queue/queue-events.service.spec.ts
- src/app/queue/queue-events.service.ts
- src/app/queue/queue-slot-container/queue-slot-container.component.html
- src/app/queue/queue-slot-container/queue-slot-container.component.spec.ts
- src/app/queue/queue-slot-container/queue-slot-container.component.ts
- src/app/queue/queue-slot-item/queue-slot-item.component.html
- src/app/queue/queue-slot-item/queue-slot-item.component.spec.ts
- src/app/queue/queue-slot-item/queue-slot-item.component.ts
- src/app/queue/queue.actions.ts
- src/app/queue/queue.effects.spec.ts
- src/app/queue/queue.effects.ts
- src/app/queue/queue.module.ts
- src/app/queue/queue.reducer.ts
- src/app/queue/queue.selectors.spec.ts
- src/app/queue/queue.selectors.ts
- src/app/queue/queue.service.spec.ts
- src/app/queue/queue.service.ts
Makes use of the new mark-as-friend system.
> feat: new friends system

- src/app/core/navigation-bar/navigation-bar.component.spec.ts
- src/app/games/game-details/game-details.component.html
- src/app/games/game-details/game-details.component.spec.ts
- src/app/games/game-details/game-details.component.ts
- src/app/games/join-game-info/join-game-info.component.spec.ts
- src/app/players/add-player-ban/add-player-ban.component.spec.ts
- src/app/players/player-details/player-details.component.spec.ts
- src/app/profile/profile.reducer.ts
- src/app/profile/profile.selectors.spec.ts
- src/app/profile/profile.selectors.ts
- src/app/queue/queue-slot-container/queue-slot-container.component.spec.ts
Simplifies the profile state and updates some tests.
> refactor: profile state cleanup

- src/app/profile/models/profile.ts
- src/app/profile/profile.selectors.spec.ts
- src/app/profile/profile.selectors.ts
- src/app/profile/settings/settings.component.html
- src/app/profile/settings/settings.component.scss
- src/app/profile/settings/settings.component.spec.ts
- src/app/profile/settings/settings.component.ts
- src/app/shared/window-helper.service.spec.ts
- src/app/shared/window-helper.service.ts
- src/app/twitch/twitch.effects.ts
- src/app/twitch/twitch.service.spec.ts
- src/app/twitch/twitch.service.ts
- src/assets/TwitchGlitchWhite.svg
Adds the ability to link the twitch.tv profile.
> feat: link twitch account

- src/app/players/models/player.ts
- src/app/players/player-details/player-details.component.html
- src/app/players/player-details/player-details.component.scss
- src/app/players/player-details/player-details.component.spec.ts
- src/app/players/player-details/player-details.component.ts
- src/app/players/players.module.ts
- src/app/players/twitch-tv-profile-link.pipe.spec.ts
- src/app/players/twitch-tv-profile-link.pipe.ts
Adds a twitch.tv profile link on the player's details page.
> feat: twitch profile link

- package-lock.json
- package.json
- src/app/games/game-team-header/game-team-header.component.scss
- src/app/games/game-team-player-list/game-team-player-list.component.scss
- src/app/players/player-stats/player-stats.component.scss
- src/app/profile/settings/settings.component.scss
- src/app/queue/queue-container/queue-container.component.scss
- src/app/queue/queue-slot-item/queue-slot-item.component.scss
Get rid of unnecessary bootstrap includes in scss files.
> fix: optimize bundle size

- src/app/io/socket-factory.service.ts
https://stackoverflow.com/a/47697179/2937977
> fix: workaround socket.io xhr poll error

- src/app/games/game-details/game-details.component.spec.ts
- src/app/games/game-details/game-details.component.ts
- src/app/games/game-team-header/game-team-header.component.ts
- src/app/games/game-team-player-list/game-team-player-list.component.spec.ts
- src/app/games/games.effects.spec.ts
- src/app/games/games.effects.ts
- src/app/games/games.selectors.spec.ts
- src/app/games/games.selectors.ts
- src/app/games/models/game-player.ts
- src/app/games/models/game.ts
- src/app/games/models/tf2-team.ts
Adapt to changes made in the Game model that the server introduces in the new version.
> feat: handle new Game model

- package-lock.json
- package.json
- src/app/games/games.selectors.ts
- src/app/shared/safe-mumble-url.pipe.ts
Gets rid of the url-parse dependency, making use of the native URL class.
> fix: get rid of url-parse

- src/app/players/player-avatar/player-avatar.component.html
- src/app/twitch/twitch-stream-list-item/twitch-stream-list-item.component.html
Enables the use of `Cross-Origin-Embedder-Policy: require-corp` header.
> fix: mark crossorigin resources

- karma.conf.js
- package-lock.json
- package.json
Replace karma-coverage-instabul-reporter with karma-coverage
> fix(ci): use karma-coverage

- src/app/hall-of-fame/hall-of-fame-routing.module.ts
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.html
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.scss
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.spec.ts
- src/app/hall-of-fame/hall-of-fame/hall-of-fame.component.ts
- src/app/notifications/request-notification-permissions/request-notification-permissions.component.spec.ts
- src/app/queue/queue/queue.component.spec.ts
Rewrite the HallOfFameComponent to match the new UI spec.
> refactor: HallOfFameComponent rewrite

- src/app/game-servers/add-game-server/add-game-server.component.scss
> fix: AddGameServerComponent surface color

- src/app/players/reducers/players.reducer.ts
- src/app/queue/models/queue-slot.ts
- src/app/queue/queue.effects.spec.ts
Makes use of populated players in the queue model, since it is supported by server for some time now.
> fix: use populated queue model

- src/app/auth/is-admin.guard.spec.ts
- src/app/auth/is-admin.guard.ts
- src/app/core/navigation-bar/navigation-bar.component.html
- src/app/core/navigation-bar/navigation-bar.component.spec.ts
- src/app/core/navigation-bar/navigation-bar.component.ts
- src/app/games/game-details/game-details.component.spec.ts
- src/app/games/game-details/game-details.store.ts
- src/app/games/games.effects.spec.ts
- src/app/players/add-player-ban/add-player-ban.component.spec.ts
- src/app/profile/profile.reducer.ts
- src/app/profile/profile.selectors.spec.ts
- src/app/profile/profile.selectors.ts
- src/app/queue/queue-slot-container/queue-slot-container.component.spec.ts
Fix IsAdminGuard logic by returning a value only after the player role is truly determined.
> fix: fix IsAdminGuard

- src/app/admin/admin-item-list/admin-item-list.component.html
- src/app/admin/admin-routing.module.ts
- src/app/admin/admin.module.ts
- src/app/admin/document-edit/document-edit.component.html
- src/app/admin/document-edit/document-edit.component.scss
- src/app/admin/document-edit/document-edit.component.spec.ts
- src/app/admin/document-edit/document-edit.component.ts
- src/app/admin/map-pool-edit/map-pool-edit.component.html
- src/app/documents/document.resolver.spec.ts
- src/app/documents/document.resolver.ts
- src/app/documents/documents.service.spec.ts
- src/app/documents/documents.service.ts
Add the possibility for admins to edit documents - for now it's only rules, but in the future more documents may come.
> feat: edit documents

- src/app/app.component.scss
- src/app/core/footer/footer.component.scss
- src/styles/global/_body.scss
Also, make footer position static rather than fixed.
> fix(css): make scrollbar always visible

- src/environments/tf2pickup.us.ts
Something happened to the invite. We're not certain exactly what.
> fix(tf2pickup.us): fix discord invite

- src/environments/tf2pickup.it.ts
The invite was broken. This one should work and not have an expiration.
> fix(tf2pickup.it): fix discord invite

- src/app/games/game-details/game-details.component.html
- src/app/games/game-details/game-details.component.spec.ts
- src/app/games/game-details/game-details.store.ts
- src/app/games/game-team-player-list/game-team-player-list.component.html
- src/app/games/game-team-player-list/game-team-player-list.component.spec.ts
- src/app/games/game-team-player-list/game-team-player-list.component.ts
- src/app/games/games.effects.spec.ts
- src/app/games/games.effects.ts
- src/app/games/models/game-slot.ts
- src/app/games/models/game.ts
- src/app/games/models/resolved-game-slot.ts
- src/app/games/order-tf2-classes.pipe.spec.ts
- src/app/games/order-tf2-classes.pipe.ts
- src/app/players/player-details-game-list/player-details-game-list.component.spec.ts
- src/app/players/player-details-game-list/player-details-game-list.component.ts
- src/app/queue/friend-flags.ts
- src/app/queue/models/queue-slot.ts
- src/app/queue/queue-class-slot-list/queue-class-slot-list.component.spec.ts
- src/app/queue/queue-slot-container/queue-slot-container.component.spec.ts
- src/app/queue/queue-slot-container/queue-slot-container.component.ts
- src/app/queue/queue-slot-item/queue-slot-item.component.html
- src/app/queue/queue-slot-item/queue-slot-item.component.spec.ts
- src/app/queue/queue-slot-item/queue-slot-item.component.ts
- src/app/queue/queue.effects.spec.ts
- src/app/queue/queue.selectors.spec.ts
- src/app/queue/queue.selectors.ts
- src/app/selectors.spec.ts
Update models to handle new API introduced in [server's version 9](https://github.com/tf2pickup-org/server/pull/1660).
> fix(*): update models to server v9

- src/app/players/players.service.spec.ts
- src/app/players/players.service.ts
The old endpoint is deprecated (and doesn't work properly), so let's switch to the new one.
> fix(players): fix fetchPlayerGames() endpoint

- src/app/admin/game-servers/static-game-server-list/static-game-server-list.component.spec.ts
- src/app/admin/game-servers/static-game-server.resolver.spec.ts
- src/app/admin/game-servers/static-game-server/static-game-server.component.html
- src/app/admin/game-servers/static-game-server/static-game-server.component.spec.ts
- src/app/game-servers/models/game-server.ts
* update model
* remove customVoiceChannelName
* add game server address
> fix(admin): fix game server details page

- src/styles/main.scss
https://github.com/valor-software/ngx-bootstrap/issues/6490
> fix(css): workaround for bootstrap 5.2 tooltips

- .vscode/settings.json
- src/app/games/games.service.spec.ts
- src/app/games/games.service.ts
Adapt the new [server API](https://github.com/tf2pickup-org/server/pull/2240).
> fix(games): adapt the new game admin API

- .github/workflows/build-docker-image.yml
BREAKING CHANGE: docker image names are changed
> feat(build): move docker images to gh packages

- src/app/player-action-logs/player-action-logs/player-action-logs.component.html
Added missing elements and classes to player-action-logs.
Replaced "Steam ID" with "SteamID64" for disambiguation.
> fix: improved player action logs

- src/app/players/add-player-ban/add-player-ban.component.html
- src/app/players/add-player-ban/add-player-ban.component.ts
> Added ban duration input types

- src/app/auth/auth-error/auth-error.component.html
- src/app/auth/auth-error/auth-error.component.scss
- src/app/auth/auth-error/auth-error.component.spec.ts
- src/app/auth/auth-error/auth-error.component.ts
Dependent on the production docs being updated
> Changed error styling and added link to docs
